### ISSUE TITLE
Not working in Sketch 70.2

### ISSUE THREAD

**Issue by danigilme** [kbirgoren/sketch-json-translator#10]
Hi kbirgoren, thanks for building this! It's really useful. But now, when I try to use it, I cannot choose the JSON file because nothing happens.

Here is a mini video:
[https://cln.sh/Ipu2we](https://cln.sh/Ipu2we)

Hope you or someone can solve this!
Thanks 👍

**Comment by kbirgoren** [comment]
Hey @danigilme,

Thanks for your interest.

It's been a very long time since I developed this plugin.  I guess many new version has been released by Sketch during that time and I could not have any time to keep the plugin up to date with new versions. 

Unfortunately I don't expect to update the plugin soon either. So sorry for that :(
