### ISSUE TITLE
Multiple instances of same nested symbols

### ISSUE THREAD

**Issue by ziyafenn** [kbirgoren/sketch-json-translator#9]
I found another bug that could be improved.

When using two or more instances of the same symbol (i.e. button) inside another symbol (i.e. modal), because there is no way to give a unique name to text layers of the same button instances, it is impossible to update text layers of the buttons.

Is there any workaround? 

Thanks.

**Comment by kbirgoren** [comment]
Hey @ziyafenn,

Thanks for your interest.

It's been a very long time since I developed this plugin.  I guess many new version has been released by Sketch during that time and I could not have any time to keep the plugin up to date with new versions. 

Unfortunately I don't expect to update the plugin soon either. So sorry for that :(
